apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: ""
  policy.matchMode: glob
  scopes: "[groups]"
  policy.csv: |
    p, role:argocd-admin, applications, *, */*, allow
    p, role:argocd-admin, projects, *, *, allow
    p, role:argocd-admin, clusters, get, *, allow
    p, role:argocd-admin, repositories, *, *, allow
    p, role:argocd-admin, logs, get, *, allow
    p, role:argocd-admin, exec, create, */*, allow

    p, role:argocd-readonly, applications, get, */*, allow
    p, role:argocd-readonly, applications, list, */*, allow
    p, role:argocd-readonly, clusters, get, *, allow
    p, role:argocd-readonly, repositories, get, *, allow
    p, role:argocd-readonly, logs, get, *, allow
    {{- range .Values.admin }}
    g, {{ . }}, role:argocd-admin
    {{- end }}
    {{- range .Values.readonly }}
    g, {{ . }}, role:argocd-readonly
    {{- end }}
